# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
        kaggle: 2
        breast cancer: 5
        mammography: 5
        segmentation: 5
        detection: 3
        classification: 3

# 通知の閾値
score_threshold: 3
